name: Build and Deploy MkDocs

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install "mkdocs-material[imaging]"

      - name: Build site
        run: mkdocs build --site-dir=./public

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pages
        uses: actions/deploy-pages@v1